#!/bin/bash -e
log-helper level eq trace && set -x

# Usage:
# add-multiprocess-stack

log-helper info "Install the multiprocess stack: runit, syslog-ng-core, logrotate and cron"
/container/tools/add-services-available :runit :syslog-ng-core :logrotate :cron
touch /container/multiprocess_stack_added
