#!/bin/bash -e
log-helper level eq trace && set -x

# Usage:
# add-services-available [service 1] [service 2] ...

SERVICE_DIR="/container/services"
SERVICE_AVAILABLE_DIR="/container/services-available"
DOWNLOAD_FILENAME="download.sh"

for i in "$@"
do
    log-helper info "add-services-available: ${i}"
    if  [ -d "${SERVICE_AVAILABLE_DIR}/${i}" ]; then
        
        if [ -f "${SERVICE_AVAILABLE_DIR}/${i}/${DOWNLOAD_FILENAME}" ]; then
            log-helper info "run ${SERVICE_AVAILABLE_DIR}/${i}/${DOWNLOAD_FILENAME}"
            eval "${SERVICE_AVAILABLE_DIR}/${i}/${DOWNLOAD_FILENAME}"

            log-helper info "remove ${SERVICE_AVAILABLE_DIR}/${i}/${DOWNLOAD_FILENAME}"
            rm -f "${SERVICE_AVAILABLE_DIR}/${i}/${DOWNLOAD_FILENAME}"
        fi
        
        log-helper info "move ${SERVICE_AVAILABLE_DIR}/${i} to ${SERVICE_DIR}/${i}"
        mv "${SERVICE_AVAILABLE_DIR}/${i}" "${SERVICE_DIR}/${i}"
        
    else
        log-helper info "${i} not found in ${SERVICE_AVAILABLE_DIR}/${i}"
        exit 1
    fi
done
