#!/bin/bash -e
log-helper level eq trace && set -x

# Usage:
# install-debug-tool [extra package 1] [extra package 2] ...

TO_INSTALL=(curl less procps psmisc strace vim)

log-helper info "Install debug tools:" "${TO_INSTALL[@]}"

if [ -n "${*}" ]; then
    log-helper info "with extra package(s): ${*}"
    TO_INSTALL+=("$@")
fi

/container/tools/packages-index-update
/container/tools/packages-install-clean "${TO_INSTALL[@]}"
