FROM ${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_TAG}

# Uncomment to add container environment variables used by generator
# and provide templates to extend your image
# ARG IMAGE_NAME=my-compagny
# ARG IMAGE_TAG=1.0.0
# ENV CONTAINER_IMAGE_NAME=${IMAGE_NAME} \
#     CONTAINER_IMAGE_TAG=${IMAGE_TAG}

RUN packages-index-update \
    && packages-install-clean \
        [....]

COPY services /container/services

RUN install-services

COPY environment /container/environment/${ENVIRONMENT_DIRECTORY}
