#!/bin/bash -e
log-helper level eq trace && set -x

set -o pipefail

# Usage:
# packages-index-clean

log-helper info "Clean packages index"
apt -qy autoremove 2>&1 | log-helper debug
apt clean 2>&1 | log-helper debug
rm -rf /var/lib/apt/lists/*
