#!/bin/bash -e
log-helper level eq trace && set -x

set -o pipefail

# Usage:
# packages-install [package 1] [package 2] ...

export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive

ARGS="$*"
NO_RECOMMENDS="--no-install-recommends"
RECOMMENDS="--install-recommends"
if [[ $ARGS =~ $RECOMMENDS ]]; then
    NO_RECOMMENDS=""
    ARGS=${ARGS//${RECOMMENDS}/}
fi

log-helper info "Install packages: ${ARGS}"
eval apt install -qy "${NO_RECOMMENDS}" "${ARGS}" 2>&1 | log-helper info
